doEvalVar=True, for test cases for XmippProtExtractParticles (#1022) (#1024)
extractParticles test was failling because:
File
"/home/agarcia/miniconda/envs/scipion3/lib/python3.8/unittest/case.py",
line 765, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : Particle has not scoreByVariance
attribute.

The reason, particle evaluation _doEvalVar_ as optional since:
https://github.com/I2PC/scipion-em-xmipp/commit/8e3251396e48cc1765c4990745ce33cdcc27406b